[bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"src/m4b_converter/__init__.py" = [
    '__version__ = "{version}"',
]