[bumpver]
current_version = "0.3.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "global"

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"src/m4b_converter/__init__.py" = [
    '__version__ = "{version}"',
]
"src/m4b_converter/cli/version.py" = [
    '__version__ = "{version}"',
]